#!/bin/sh
#TODO: configure git hooks

RED='\033[0;31m'
NC='\033[0m'

echo "Running tslint..."

#TODO: check only changed files
npx tslint -p ./tsconfig.json

let tslintExitCode=$?
if [ $tslintExitCode -ne 0 ]
then
	echo -e "${RED}Tslint check failed!
	${NORMAL}${NC}Fix errors before commit."
fi

exit $tslintExitCode
